import nodemailer from "nodemailer";

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.GMAIL_ADDRESS,
    pass: process.env.GMAIL_APP_PASSWORD,
  },
});

export interface ReportEmailInput {
  toEmail: string;
  toName: string;
  patientName: string;
  dateRange: string;
  pdfBuffer: Buffer;
}

export async function sendReportEmail(input: ReportEmailInput): Promise<void> {
  await transporter.sendMail({
    from: `"Vela Vision" <${process.env.GMAIL_ADDRESS}>`,
    to: input.toEmail,
    subject: `Care Report for ${input.patientName}`,
    text: `Hi ${input.toName},\n\nPlease find attached the care report for ${input.patientName} covering ${input.dateRange}.\n\nGenerated by Vela Vision.`,
    attachments: [{
      filename: `${input.patientName.replace(/\s+/g, "_")}_Care_Report.pdf`,
      content: input.pdfBuffer,
      contentType: "application/pdf",
    }],
  });
}
