import { describe, it, expect } from "vitest";
import { buildDailyRule, buildWeeklyRule } from "../server-core/recurrence";
import { toExpoCalendarRecurrenceRule } from "./appleCalendarRecurrence";

describe("toExpoCalendarRecurrenceRule", () => {
  it("returns undefined for a null/undefined rule (one-off event)", () => {
    expect(toExpoCalendarRecurrenceRule(null)).toBeUndefined();
    expect(toExpoCalendarRecurrenceRule(undefined)).toBeUndefined();
  });

  it("converts a daily rule generated by the app's own builder", () => {
    const rrule = buildDailyRule();
    expect(toExpoCalendarRecurrenceRule(rrule)).toEqual({ frequency: "daily" });
  });

  it("converts a weekly Mon+Wed rule, mapping rrule's own weekday numbering to expo-calendar's", () => {
    // buildWeeklyRule uses 0=Sunday..6=Saturday, so [1, 3] is Monday + Wednesday.
    const rrule = buildWeeklyRule([1, 3]);
    const result = toExpoCalendarRecurrenceRule(rrule);
    // rrule's own numbering: MO=0, WE=2. expo-calendar's DayOfTheWeek: Monday=2, Wednesday=4.
    expect(result).toEqual({
      frequency: "weekly",
      daysOfTheWeek: [{ dayOfTheWeek: 2 }, { dayOfTheWeek: 4 }],
    });
  });

  it("converts a weekly Sunday+Saturday rule, exercising the wraparound of the day mapping", () => {
    // 0=Sunday, 6=Saturday in this app's convention.
    const rrule = buildWeeklyRule([0, 6]);
    const result = toExpoCalendarRecurrenceRule(rrule);
    // rrule's own numbering: SU=6, SA=5 (rrule preserves insertion order, so byweekday is [SA, SU] here).
    // expo-calendar's DayOfTheWeek: Saturday=7, Sunday=1.
    expect(result).toEqual({
      frequency: "weekly",
      daysOfTheWeek: [{ dayOfTheWeek: 1 }, { dayOfTheWeek: 7 }],
    });
  });
});
